version: '2'
services:
  flexoriginals:
    container_name: flexoriginals
    image: flexoriginals
    restart: always
    build: .
    ports:
      - '3000:3000'
      - '3333:3333'
      - '3355:3355'
    links:
      - mongo
    volumes:
      - ./uploads:/usr/src/uploads
      - ./common:/usr/src/common
      - ./server:/usr/src/server
      - ./dist:/usr/src/dist

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
